### ISSUE TITLE
Como ajudar?

### ISSUE THREAD

**Issue by victorlcampos** [socialpullrequest/socialpullrequest#1]
Bom dia,
como poderei ajudar no projeto?

**Comment by jonatasemidio** [comment]
Fala Vitor!

Realmente você é bem rápido rsrs...
Não lembro se quando eu conversei sobre essa parte com o Raphael você estava presente ... Muita coisa eu falei por email também, mas é o seguinte:

Agente tem esse desejo de ajudar projetos sociais que precisam de programadores, eu tinha pensado em criar um site para toda uma filosofia para ir divulgando depois nas redes sociais mas esqueci que algumas coisas precisa ser iniciadas logo e o tempo vai trazer o amadurecimento, logo crie um README sem avisar o Raphael, mas mandei um email para ele hoje cedo rsrs para ver o que ele acha.

Minha intenção é marcar um outro almoço para falar sobre isso... Assim que ele responder eu mando um email com vocês em cópia.

Porém, já adiantando alguns passos...
Existem algumas organizações que já possuem app no github como médicos sem fronteiras e unicef, e podemos tanto separar um dia para resolver as issues como entrar em contato com outras organizações para ver o que elas precisam e como podemos ajudar.

**Comment by victorlcampos** [comment]
Blz, eu não estava presente não, o meu feed do github me avisou do projeto e eu achei maneiro =).
Me adiciona sim

**Comment by jonatasemidio** [comment]
xacumigu

**Comment by ftonato** [comment]
Bom e aqueles que não se farão presentes no almoço por estarem/viverem no sul do país (meu caso), também podem receber essas informações? :dancers:

**Comment by jonatasemidio** [comment]
Fala @ftonato!

Fico muito feliz em ver pessoas interessadas em contribuir... Quero muito começar a tocar esse projeto e o quanto antes, mas mesmo querendo iniciar logo, não quero iniciar de qualquer jeito rsrs.

Tenho o desejo de organizar as ideias principais primeiro e talvez até fazer um código de conduta para as coisas não ficarem bagunçadas.

Apesar de eu ser programador, eu gosto de conversar com as pessoas "pessoalmente" e presencialmente rsrsr, mas não nos impede de também marcarmos hangouts.

Eu fico _on_ direto no hangout, então ( @ftonato e @victorlcampos ) me mande seus emails [de preferência gmail - pois talvez eu use o docs e hangouts] para irmos trocando figurinhas!
Até o final do dia de hoje, enviarei um posicionamento mais claro de como poderemos tocar o barco.

**Comment by ftonato** [comment]
@jonatasemidio beleza, tens alguma ideia do 'layout' do projeto?
Imagino que poderia dividir as tarefas, talvez criando issues e cada um/ou mais dos membros escolhe uma/ou mais e vai fazendo, talvez fosse algo válido para "começar" o projeto?

Também pensei que pudesse existir listas de projetos que já ajudamos e projetos a ajudar.
Acredito que tudo isso já tenha sido projetado na mente de vocês, mas caso ainda não tenha sido, fica algumas dicas que acho válidas.

Sobre o e-mail, eu pouco lembro de entrar no hangouts, mas meu email de lá é ademilsonft[at]outlook[dot]com que também é meu e-mail principal.
Fico no aguardo p/ novidades ;)

**Comment by jonatasemidio** [comment]
@ftonato! Com certeza ... Teremos sim divisões de tarefas rsrs

O repositório vai ser esse mesmo e poderemos evoluir tanto a parte de apresentação/código quanto a parte filosófica com o readme, issues e wiki

Tinha falado do gmail, pois caso eu crie algum docs para evoluir em conjunto com varias pessoas vou usar o docs do drive... que ajuda muito para essas coisas ... Ele tem, controle de versão, comentário por linhas, gestão de sugestões e podemos alterar simultaneamente com uma visão clara de quem está escrevendo o que rsrsr (Ou seja, acho muito útil rsrs). Já no caso das conf de vídeo o prefiro o hangout no lugar do skype pelo simples fato de vários poderem acompanhar ao mesmo tempo e salvar o conteúdo direto no youtube caso seja algo interessante para outras pessoas que não participaram ficarem por dentro.

**Comment by ftonato** [comment]
@jonatasemidio Ah beleza!
Esse meu e-mail serve para isso também visto que cadastrei minha conta do Google com esse e-mail!

Se eu já puder ir ajudando de alguma forma, fico a disposição :+1:

**Comment by jonatasemidio** [comment]
Show!

**Comment by jonatasemidio** [comment]
> fala( @raphamorim , @victorlcampos , @ftonato , @afonsopacifer );
> - No ultimo hangout foram definido os seguintes itens:

```
- Organização
    - Definir uma logo
    - Dominio
        (socialpullrequest.org)
    - Pensar em possíveis parceiros
        - vtex
        - mozilla
        - wdev
        - dtm
        - HE:Labs
    - Definir e montar estrutura inicial do site
        - Disponibilizar a opção, submeter pra fest
        - Search pra ongs para help

Ações 
    - Desenvolva sua própria socialpullrequest fest
    - Encontre uma ong perto de você (find a ong near you)


```

Acho que agora podemos correr atraz de algumas coisas.
1 - logo ... Antes de contrarmos alguem para fazer o logo, temos que definir como gostariamos que eles fossem.

2 - Tambem poderiamos já iniciar com um sites simples.

O que acham?

**Comment by ftonato** [comment]
@jonatasemidio Poderia explicar um pouco mais sobre os tópicos filhos de `- Definir e montar estrutura inicial do site`?

2 - Lembra que outrora te enviei uma definição básica de um layout que eu havia pensado? (Se quiser posso montar aquela estrutura p/ apresentar a vocês, o que acha?)

**Comment by afonsopacifer** [comment]
Fala pessoal, alguém já pensou em quais tecnologias vamos usar para criar e manter o site?
Sei la, tipo um gerador estático da vida ou outra coisa?

**Comment by ftonato** [comment]
@afonsopacifer Havia conversado com o @jonatasemidio sobre o Jekyll e parece sempre uma boa opção!
Todavia, qualquer sugestão é bem vinda...

**Comment by afonsopacifer** [comment]
@ftonato Jekyll é bom pq ele é o mais pop, logo é mais provável que mais pessoas saibam mexe para ajudar :)
Se todos estiverem de acordo eu já posso ir criando a estrutura básica :)

**Comment by ftonato** [comment]
@afonsopacifer Acho que podes criar e submeter p/ que todos avaliem, e já possam contribuir :smile:

**Comment by jonatasemidio** [comment]
Fala @ftonato ! Realmente não ficou muito explicado rsrs...
- Submit para Fest: (Fest - é um modelo para o SPR que juntaremos uma turma para corrigir issues de apps de ongs). A idéia é cada localidade poder cadastrar o seu SPR Fest
- Search: Seria interessante, mas não necessáriamente precisa entrar na 1º versão um search para que devs localizem ongs e vise versa

---

Com relação a estrutura ... eu acho que pode sim ... não sei se alguem aqui tambem está afim de tocar o site... Eu como não sou de front geralmente pego templates prontos e altero rsrs

Mesmo assim ... Vamos ver o desenrolar dessa tarefa, pois o @raphamorim tambem é ligado nessa parada e ele deve querer tocar isso ou acompanhar bem de perto.

---

@afonsopacifer ... Realmente ... Como o @ftonato falou ... Achamos o jekyll bem interessante, mas nada nos impede de iniciar bem mais simples ... só com um template com HTML e CSS rsrs

---

Por fim, para o site, da um `fork` no [projeto do socialpullreqquest](https://github.com/socialpullrequest/socialpullrequest.github.io) que está completamente cru rsrs

**Comment by afonsopacifer** [comment]
OK, vou tentar mandar algo nesse fds, assim o @raphamorim da uma olhada no PR e já andamos com o site.

**Comment by jonatasemidio** [comment]
Show!

Em 8 de janeiro de 2016 11:19, Afonso Pacifer notifications@github.com
escreveu:

> OK, vou tentar mandar algo nesse fds, assim o @raphamorim
> https://github.com/raphamorim da uma olhada no PR e já andamos com o
> site.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/socialpullrequest/socialpullrequest/issues/1#issuecomment-170000914
> .

## 

_------------------------------------------------------------------Jonatas
Emidio_
http://santograils.org/
_------------------------------------------------------------------_
_------------------------------------------------------------------_

## http://smallactsmanifesto.org/
- Coding Dojo Rio *
  http://dojorio.org/
  https://github.com/dojorio/dojo-centro
  _------------------------------------------------------------------_

**Comment by raphamorim** [comment]
Show, se quiser posso te ajudar @afonsopacifer

**Comment by victorlcampos** [comment]
@afonsopacifer, alguma novidade?

**Comment by afonsopacifer** [comment]
@victorlcampos, Sim, vou mandar um PR com a estrutura hoje a noite ou amanha cedo :)

**Comment by ftonato** [comment]
@afonsopacifer quando fizer, dá um ping em mim por aqui, faz favor =)

**Comment by afonsopacifer** [comment]
@ftonato Pode deixar mano :)

**Comment by victorlcampos** [comment]
Boa, ai sim galera =D
"Vamo que vamo"

**Comment by jonatasemidio** [comment]
Show!

2016-01-13 10:28 GMT-02:00 Victor Campos notifications@github.com:

> Boa, ai sim galera =D
> "Vamo que vamo"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/socialpullrequest/socialpullrequest/issues/1#issuecomment-171276813
> .

## 

_------------------------------------------------------------------Jonatas
Emidio_
http://santograils.org/
_------------------------------------------------------------------_
_------------------------------------------------------------------_

## http://smallactsmanifesto.org/
- Coding Dojo Rio *
  http://dojorio.org/
  https://github.com/dojorio/dojo-centro
  _------------------------------------------------------------------_

**Comment by victorlcampos** [comment]
@afonsopacifer, teria como abrir um pull request e a gente já vai verificando como ta ficando e podemos contribuir tb?

**Comment by afonsopacifer** [comment]
@victorlcampos Sim, eu já fiz umas coisas aqui, o lance é, que quando mais eu mexia, mais parecia que o Jekyll era de mais para algo simples saka, ai acabei pensando que algo mais simples, vou mandar daqui a pouco para vcs verem.

**Comment by jonatasemidio** [comment]
Então Galera!

Existe uma outra iniciativa que estou tocando [#devopenhouse](http://devopenhouse.github.io/) e pensei em fazer em jekyll também ... mas como tive um certo problema para ajustar o template nele eu decidi botar o site no ar logo e depois com calma farei um update para jekyll se as necessidades me indicarem para isso.

No caso de estar saindo do patamar de simples sugiro botar o site no ar apontando para um blog no medium por exemplo.

**Comment by afonsopacifer** [comment]
aa, pera pera, vão ter posts? Se sim usamos Jekyll mesmo, eu achei que não teria :)

**Comment by victorlcampos** [comment]
Pois é, acho que essa issue ta ficando muito grande.
@afonsopacifer, cria um pull request e vamos levar o debate para ele

**Comment by afonsopacifer** [comment]
Blz
