### ISSUE TITLE
Icone da organização

### ISSUE THREAD

**Issue by afonsopacifer** [socialpullrequest/socialpullrequest#10]
Sei que é frescura, mas acho que o icone redondinho fica mais bonitinho :)

![spr-icon](https://cloud.githubusercontent.com/assets/6748866/12833793/2e21acbc-cb8a-11e5-8b8d-9f10dfc26356.png)

**Comment by victorlcampos** [comment]
+1

Boa afonso =)

**Comment by victorlcampos** [comment]
@jonatasemidio ou @raphamorim, podem fechar essa issue?
