### ISSUE TITLE
ONGs que serão ajudadas?

### ISSUE THREAD

**Issue by victorlcampos** [socialpullrequest/socialpullrequest#2]
Pessoal,
Gostaria de saber quais projetos vocês estão pensando em ajudar.

**Comment by jonatasemidio** [comment]
Opa .. A intenção é que essa seja uma das etapas dos encontros.

Ex: Digamos que eu conheço uma ONG que precisa muito ajustar o envio de email do seu site, alguem leva isso pro grupo #SPR, onde eles definem como poderão ajudar a ONG. Neste momento que eu entendo que a ONG vai entrar para a lista do grupo.

A intenção é ter uma lista enxuta de ongs que realmente já estão sendo ajudadas. Ao contrario teremos uma lista muito grande de ONGs que podem nem estar ativas.

Resumindo: O projeto será definido no dia do encontro. Inclusive já podemos levar para esse encontro uma lista de ONGs, mas a ideia é que algo já esteja encaminhado.

Lembrando que isso é a minha opinião e estou aqui para ouvir vocês também.

**Comment by jonatasemidio** [comment]
Criei o [FAQS](https://github.com/socialpullrequest/socialpullrequest/blob/master/FAQS.md), para que conforme as duvidas forem aparecedo e acharmos necessário, passaremos para esse arquivo.
