### ISSUE TITLE
Criar uma Wiki para melhor organização

### ISSUE THREAD

**Issue by ftonato** [socialpullrequest/socialpullrequest#3]
Hoje temos a estrutura do projeto organizada em um arquivo, como a estrutura tente a crescer conforme o projeto cresce, sugiro a utilização da Wiki, assim conseguimos dividir os conteúdos e manter tudo organizado.

**Comment by jonatasemidio** [comment]
Fala @ftonato,

Eu quero fazer uma wiki, mas como minha intenção era iniciar logo e de uma maneira que outros pudessem opinar, fiz no projeto, pois assim pessoas podem mandar issues e PR.

Com relação a wiki do github eu tenho duas dúvidas:
1 - ainda não vi, mas alguém sabe me dizer se fica fácil de visualizar uma issue apontada para algum paragrafo da wiki;
2 - para que a pessoa possa contribuir com a wiki ela precisa ter permissão de commit no projeto todo ou podemos dar permissões especificas?
Já adiantando... Caso isso não seja possível, talvez seria interessante criar um projeto só para a filosofia do SPR (levando em consideração que o .md já nos permite criar links, assim podemos estruturar o conteúdo em diferentes documentos). Acho que isso facilitaria a evolução do documento.

@raphamorim @victorlcampos @ftonato O que vocês acham?

**Comment by victorlcampos** [comment]
Acredito que seja possível sim...
Acho que poderia ter também explicando como uma ong entra em contato.

**Comment by ftonato** [comment]
Fala @jonatasemidio, beleza?

Cara, creio que com o site no ar, provavelmente não será necessário ter uma wiki, quem sabe assim que o projeto crescer possámos retomar tal _issue_, mas até lá podes encerrar ela o/

**Comment by jonatasemidio** [comment]
Faz sentido
