### ISSUE TITLE
Definir Logo

### ISSUE THREAD

**Issue by victorlcampos** [socialpullrequest/socialpullrequest#4]
Coloquem aqui suas sugestões(esboço) de logo, antes da gente enviar para um designer fazer a versão final.

**Comment by victorlcampos** [comment]
@jonatasemidio

**Comment by jonatasemidio** [comment]
#### Acho interessante se mesclarmos na lugo dois itens que lembrem tecnologia e serviço social
- silhueta do octocat do github com uma auréola de anjo
- uma tag com um coração dentro
- um coração com uma tag dentro
- um óculos com uma auréola
- um robo com coração

`Fiz alguns testes:`
<img src="https://lh6.googleusercontent.com/-u9fmbBEHUmA/Vo5v-Z6_0KI/AAAAAAAACMo/sro_x2nWYg8/w1499-h845-no/2016-01-07.png">

**Comment by victorlcampos** [comment]
(4) ou (7)

**Comment by victorlcampos** [comment]
@jonatasemidio, sugiro abrir um pedido no freelancer(https://www.br.freelancer.com/dashboard/), só usei e gastei 50 doletas.

Coloca isso na planilha de custos e a gente divide, depois a gente tenta recuperar com doações.
Essa issue está travando o layout do projeto.

**Comment by ftonato** [comment]
@victorlcampos sobre a issue estar travando o layout do projeto, sugiro que por hora seja usado o mesmo logo que está nao organização, o que acha?

![16313470](https://cloud.githubusercontent.com/assets/5417662/12429972/358a9aee-bed4-11e5-8203-810ef72e7ac3.png)

**Comment by victorlcampos** [comment]
@afonsopacifer

**Comment by afonsopacifer** [comment]
@ftonato, @victorlcampos OK, 
vou adicionar um layout simples usando essa logo la no PR.

**Comment by raphamorim** [comment]
Sério, se a gente perder tempo com isso. O projeto não vai sair. Por isso eu sugiro usarmos uma logomarca simples. Fiz uma aqui, se não curtirem enviem suas sugestões ou opções. 

![untitled-1](https://cloud.githubusercontent.com/assets/3630346/12660224/d2cfed96-c5f9-11e5-85f3-0fde5602ad75.jpg)

**Comment by victorlcampos** [comment]
+1

Só mudaria para vermelho e amarelo, tinha curtido aquela tonalidade

**Comment by raphamorim** [comment]
Não curto muito vermelho e amarelo pra web. Pra causas mais sérias eu prefiro uma cor e branco/preto para complementar (ex: vermelho e branco, azul e branco, verde e branco).

**Comment by victorlcampos** [comment]
Então fico com azul e braco... =)

**Comment by victorlcampos** [comment]
@afonsopacifer, dando ok a gente fecha essa issue

**Comment by afonsopacifer** [comment]
Acho que o importante são as atitudes que serão tomadas a partir desse projeto, o logo é um mero detalhe, então por mim está mais que **OK**.

OBS: @raphamorim Designer Gráfico? Print.... (vingança do dia no Starbucks :P)
