### ISSUE TITLE
Criação do site

### ISSUE THREAD

**Issue by jonatasemidio** [socialpullrequest/socialpullrequest#6]
Fala galera!

Em um determinado momento, na issue #1 passamos a falar só sobre o site e decidimos criar outra issue para isso.

O template em jekyll está sendo feito.

OBS: Vamos focar no start do projeto, o site pode ser simples em estrutura ("simples em estrutura" Usem seus conhecimentos para que o site possa ficar apresentável rsrs)

Basicamente ele precisa ter o titulo, logo, local com a manifestação. As outras partes que com certeza existem podem ficar para um segundo tiro!

**Comment by victorlcampos** [comment]
Não é melhor abrir um pulo request? Assim vamos acompanhando os commits?

**Comment by raphamorim** [comment]
:+1:  Também prefiro assim.

**Comment by victorlcampos** [comment]
@raphamorim, assim como?

**Comment by raphamorim** [comment]
prefiro por "pulo request" haha

**Comment by raphamorim** [comment]
Mais fácil e a gente ainda pede mudanças no próprio desenvolvimento. Na issue a gente vai bater muita boca até chegar num final

**Comment by victorlcampos** [comment]
@afonsopacifer, poderia abrir o PR?

**Comment by afonsopacifer** [comment]
Pronto.
https://github.com/socialpullrequest/socialpullrequest.github.io/pull/1

**Comment by victorlcampos** [comment]
closes #6

**Comment by victorlcampos** [comment]
resolve #6
